<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Quotation {{ $quotation->quote_number }}</title>
    <style>
        * { box-sizing: border-box; }
        body { font-family: Arial, sans-serif; margin: 24px; color: #111827; font-size: 13px; }
        .row { display: flex; justify-content: space-between; margin-bottom: 12px; gap: 24px; }
        .brand { font-size: 20px; margin: 0 0 6px; }
        .text-muted { color: #6b7280; }
        .meta { width: 100%; margin-top: 6px; border-collapse: collapse; }
        .meta td { padding: 2px 0; border: none; vertical-align: top; }
        table { width: 100%; border-collapse: collapse; margin-top: 14px; }
        th, td { border: 1px solid #d1d5db; padding: 8px; text-align: left; vertical-align: top; }
        th { background: #f3f4f6; font-weight: 700; }
        th:last-child, td:last-child { text-align: right; }
        .totals { margin-top: 16px; width: 340px; margin-left: auto; border-collapse: collapse; }
        .totals td { border: none; padding: 4px 0; }
        .totals tr:last-child td { border-top: 1px solid #111827; padding-top: 8px; }
        .footer-note { margin-top: 24px; font-size: 11px; color: #6b7280; }

        @page { margin: 20mm 14mm; }
        @media print {
            body { margin: 0; }
            .no-print { display: none !important; }
        }
    </style>
</head>
<body>
    @if(($renderMode ?? 'print') === 'print')
        <div class="no-print" style="margin-bottom: 14px; text-align: right;">
            <button onclick="window.print()" style="padding: 8px 12px; border: 1px solid #d1d5db; background: #fff; cursor: pointer;">
                Print Now
            </button>
        </div>
    @endif

    <div class="row">
        <div>
            <h2 class="brand">{{ config('brand.name') }} Quotation</h2>
            <table class="meta">
                <tr><td><strong>Quote #</strong></td><td>{{ $quotation->quote_number }}</td></tr>
                <tr><td><strong>Status</strong></td><td>{{ ucfirst($quotation->status) }}</td></tr>
                <tr><td><strong>Agency</strong></td><td>{{ $quotation->agency?->name ?: '-' }}</td></tr>
                <tr><td><strong>Created</strong></td><td>{{ $quotation->created_at?->format('d M Y') }}</td></tr>
            </table>
        </div>
        <div>
            <table class="meta">
                <tr><td><strong>Customer</strong></td><td>{{ $quotation->customer_name ?: '-' }}</td></tr>
                <tr><td><strong>Email</strong></td><td>{{ $quotation->customer_email ?: '-' }}</td></tr>
                <tr><td><strong>Phone</strong></td><td>{{ $quotation->customer_phone ?: '-' }}</td></tr>
                <tr><td><strong>Travel</strong></td><td>{{ $quotation->travel_date?->format('d M Y') ?: '-' }}</td></tr>
            </table>
        </div>
    </div>

    <table>
        <thead>
            <tr><th>Item</th><th>Description</th><th>Amount</th></tr>
        </thead>
        <tbody>
        @forelse($quotation->items as $item)
            <tr>
                <td>{{ strtoupper(str_replace('_', ' ', $item->item_type)) }}</td>
                <td>{{ $item->description ?: $item->title }}</td>
                <td>{{ number_format((float) $item->total_price, 2) }} {{ $quotation->currency }}</td>
            </tr>
        @empty
            <tr>
                <td colspan="3" class="text-muted">No line items available.</td>
            </tr>
        @endforelse
        </tbody>
    </table>

    <table class="totals">
        <tr><td>Subtotal</td><td>{{ number_format((float) $quotation->subtotal, 2) }} {{ $quotation->currency }}</td></tr>
        <tr><td>Discount</td><td>{{ number_format((float) $quotation->discount_amount, 2) }} {{ $quotation->currency }}</td></tr>
        <tr><td><strong>Grand Total</strong></td><td><strong>{{ number_format((float) $quotation->total_amount, 2) }} {{ $quotation->currency }}</strong></td></tr>
    </table>

    <p class="footer-note">
        This quotation is system generated by {{ config('brand.name') }} portal.
    </p>

    @if(($renderMode ?? 'print') === 'print')
        <script>window.print();</script>
    @endif
</body>
</html>
